config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resource :dashboard, only: [:show]
  root 'static_pages#index'
  get 'privacy', to: 'static_pages#privacy'
  get 'careers', to: 'static_pages#careers'
  get 'team', to: 'static_pages#team'
  resources :courses, only: [:index, :show] do
    resources :enrollments, only: :create
  end
  resources :lessons, only:[:show]
  namespace :instructor do
    resources :lessons, only: [:update]
    resources :sections, only: [:update] do
      resources :lessons, only: [:create]
    end
    resources :courses, only: [:new, :create, :show] do
      resources :sections, only: [:create]
     
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
mount_uploader :image, ImageUploader


 belongs_to :user
 has_many :sections
 has_many :enrollments

  validates :title, presence: true
  validates :description, presence: true
  validates :cost, presence: true, numericality: {greater_than_or_equal_to: 0}

  def free?
    cost.zero?
  end

  def premium?
    ! free?
  end
  
end

app/models/enrollment.rb
class Enrollment < ApplicationRecord
  belongs_to :course
  belongs_to :user
end

app/models/lesson.rb
class Lesson < ApplicationRecord
belongs_to :section
mount_uploader :video, VideoUploader

  include RankedModel
    ranks :row_order, with_same: :section_id

  def next_lesson
    lesson = section.lessons.where("row_order > ?", self.row_order).rank(:row_order).first
    if lesson.blank? && section.next_section
      return section.next_section.lessons.rank(:row_order).first
    end

    return lesson
  end

end

app/models/section.rb
class Section < ApplicationRecord
 include RankedModel
  belongs_to :course
  has_many :lessons

 
  ranks :row_order, :with_same => :course_id

  def next_section
    section = course.sections.where("row_order > ?", self.row_order).rank(:row_order).first
    return section
  end


end

app/models/user.rb
class User < ApplicationRecord
  has_many :courses
  has_many :enrollments
  has_many :enrolled_courses, through: :enrollments, source: :course

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def enrolled_in?(course)
    enrolled_courses = []
    enrollments.each do |enrollment|
      enrolled_courses << enrollment.course
    end

    return enrolled_courses.include?(course)
  end

end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
   
   def index
   @courses = Course.all
   end
   
   def show
    @course = Course.find(params[:id])
   end

   

end   

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController

   before_action :authenticate_user!

  def show
  end
end

app/controllers/enrollments_controller.rb
class EnrollmentsController < ApplicationController
before_action :authenticate_user!

  def create
       if current_course.premium?
        
  
# Amount in cents
      @amount = (current_course.cost * 100).to_i

    customer = Stripe::Customer.create(
      email: params[:stripeEmail],
      source: params[:stripeToken]
    )

    charge = Stripe::Charge.create(
      customer: customer.id,
      amount: @amount,
      description: 'Flixter Premo Content',
      currency: 'usd'
    )

  end
  current_user.enrollments.create(course: current_course)  
  redirect_to course_path(current_course)
  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to root_path
  end

end

 private

  def current_course
    @current_course ||= Course.find(params[:course_id])
  end

app/controllers/instructor/courses_controller.rb
class Instructor::CoursesController < ApplicationController
   before_action :authenticate_user!
    before_action :require_authorized_for_current_course, only: [:show]
  
  def new
    @course = Course.new
  end 

  def show
    @course = Course.find(params[:id])
  end

  def create
    @course = current_user.courses.create(course_params)
     if @course.valid?
      redirect_to instructor_course_path(@course)
    else
      render :new, status: :unprocessable_entity
    end
  end

    def show
      @section = Section.new
      @lesson = Lesson.new
    end
 
  private

  def require_authorized_for_current_course
    if current_course.user != current_user
      render plain: "Unauthorized", status: :unauthorized
    end
  end

   helper_method :current_course
  def current_course
    @current_course ||= Course.find(params[:id])
  end

  def course_params
    params.require(:course).permit(:title, :description, :cost, :image)
  end
end

app/controllers/instructor/lessons_controller.rb
class Instructor::LessonsController < ApplicationController
  before_action :authenticate_user!
  before_action :require_authorized_for_current_section, only: [:create]
  before_action :require_authorized_for_current_lesson, only: [:update]
    
   

    def create
    @lesson = current_section.lessons.create(lesson_params)
    redirect_to instructor_course_path(current_section.course)
    end

    def update
        current_lesson.update_attributes(lesson_params)
        render plain: 'updated!'
    end

  private

  def require_authorized_for_current_lesson
    if current_lesson.section.course.user != current_user
      render plain: 'Unauthorized', status: :unauthorized
    end
  end

  def current_lesson
    @current_lesson ||= Lesson.find(params[:id])
  end

    def require_authorized_for_current_section
      if current_section.course.user != current_user
        return render plain: 'Unauthorized', status: :unauthorized
      end
    end

  helper_method :current_section
    def current_section
    @current_section ||= Section.find(params[:section_id])
    end

    def lesson_params
    params.require(:lesson).permit(:title, :subtitle, :video, :row_order_position)
  end
end
 

app/controllers/instructor/sections_controller.rb
class Instructor::SectionsController < ApplicationController
    before_action :authenticate_user!
  before_action :require_authorized_for_current_course, only: [:create]
  before_action :require_authorized_for_current_section, only: [:update]

  def create
    @section = current_course.sections.create(section_params)
    redirect_to instructor_course_path(current_course)
  end

   def update
    current_section.update_attributes(section_params)
    render plain: 'updated!'
  end

  private

  def require_authorized_for_current_course
    if current_course.user != current_user
      render plain: "Unauthorized", status: :unauthorized
    end
  end

  def current_section
    @current_section ||= Section.find(params[:id])
  end

  helper_method :current_course
  def current_course
  if params[:course_id]
    @current_course ||= Course.find(params[:course_id])
  else
    current_section.course
  end
end

  def section_params
    params.require(:section).permit(:title)
  end
end
 
 
 
 
 
 
 
 


  

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController

  before_action :authenticate_user!
  before_action :require_authorized_for_current_lesson

  def show
  end


  private

  def require_authorized_for_current_lesson
     if !current_user.enrolled_in?(current_lesson.section.course)
      redirect_to course_path(current_lesson.section.course), alert: "You must be enrolled to view this lesson."
    end
  end

  helper_method :current_lesson
  def current_lesson
    @current_lesson ||= Lesson.find(params[:id])
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
def index
  end

  def privacy
  end

  def careers
  end

  def team
  end  
end

app/views/courses/index.html.erb
<br />

<div class="booyah-box col-10 offset-1">
  <h1 class="text-center">Learn something today</h1>

  <hr />
  <% @courses.each do|course| %>
  
    <% if course.image.present?%>

     <%= image_tag course.image.url, class: 'img-fluid' %>
    <%end%>

    <h2 class="text-center">
      <%= link_to course.title, course_path(course) %>
    </h2>
    
    <br />
    <div class="row">
      <div class="col-sm-8 col-12">
        <%= course.description %>
      </div>
    </div>
    <div class="col-sm-4 col-12 text-center">
       <%= link_to 'More Details...', course_path(course), class: 'btn btn-primary btn-large' %>
    </div>
     <br class="clr" />
  <% end %>
</div>

app/views/courses/show.html.erb
<br />

<div class="booyah-box col-10 offset-1">
  <h1><%= @course.title %></h1>
  <% if @course.image.present?%>
   <%= image_tag @course.image.url, class: 'img-fluid' %>
   <%end%>
  <br />
     <div class="text-center">
    <%= link_to 'Add a new section...',  class: 'btn btn-primary btn-lg' %>
  </div>
  
   <ul>
    <% @course.sections.each do |section| %>
      <li>
        <%= section.title %>
      </li>
    <% end %>
  </ul>
</div> 
 
  <br />
  <div class="row">
   <div class="col-sm-4 col-12 text-center">
 <div class="col-sm-4 col-12">
  <span class="badge badge-default">
    <%= number_to_currency @course.cost %>
  </span>
   <% if current_user && current_user == @course.user %>
      <br />
      <br />
      <%= link_to 'Administer', instructor_course_path(@course), class: 'btn btn-danger btn-large' %>
    <% end %>

      <br />
      <br />
       <% if current_user %>
    <% if current_user.enrolled_in?(@course) %>
        <h3 class="badge badge-info">You Are Enrolled!</h3>
      <% else %>
        
       <% if @course.free? %>
         <%= link_to 'Enroll', course_enrollments_path(@course), class: 'btn btn-primary', method: :post %>
         <% else %>
         <%= form_tag course_enrollments_path(@course) do %>
        <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
                data-email="<%= current_user.email %>"
                data-description="<%= @course.title %> (<%= number_to_currency @course.cost %>)"
                data-amount="<%= (@course.cost * 100).to_i %>"
                data-locale="auto"></script>
      < <% end %>
      <% end %>
    <% end %>
  <%else%>
    <h3 class="badge badge-info">Sign In to Enroll!</h3>
  <% end %>
</div>
 
  <div class="col-sm-8 col-12">
    <%= @course.description %>
    </div>
  </div>
<div class="col-12">
     <% @course.sections.rank(:row_order).each do |section| %>
    <br /><br />
       <div class="section">
        <h3>
          <%= section.title %>
        </h3>
        <% section.lessons.rank(:row_order).each do |lesson| %>
  <div class="col-12 col-sm-6">
    <div class="lesson text-center">
      <br />
            <%= link_to lesson_path(lesson) do %>
              <b><%= lesson.title %></b>
              <br />
              <%= lesson.subtitle %>
            <% end %>
          </div>
        </div>
        <% end %>
      </div>
    </div>
    <% end %>
  </div>
</div> 
 

app/views/dashboards/show.html.erb
<br />

<div class="booyah-box col-10 offset-1">
  <h1>What I'm Learning</h1>
  <% current_user.enrolled_courses.each do |course| %>
    <h3 class="text-center">
      <%= link_to course.title, course_path(course) %>
    </h3>
    <br />
    <%= image_tag course.image.url, class: 'img-fluid' unless course.image.url.nil? %>
    <br />
   <div class="row">
      <div class="col-12 col-sm-8">
        <%= course.description %>s
      </div>
      <div class="col-12 col-sm-4 text-center">
        <%= link_to "More Info...", course_path(course), class: 'btn btn-lg btn-primary' %>
      </div>
    </div>
    <hr class="col-8 offset-2">
    <br class="clr" />
  <% end %>


<h1>What I'm Teaching</h1>
<% current_user.courses.each do |course| %>
  <h3 class="text-center">
    <%= link_to course.title, course_path(course) %>
  </h3>
  <br />
   <%= image_tag course.image.url, class: 'img-fluid' unless course.image.url.nil? %>
  <br />
  <div class="row">
    <div class="col-12 col-sm-8">
      <%= course.description %>
    </div>
    <div class="col-12 col-sm-4 text-center">
      <%= link_to "More Info...", course_path(course), class: 'btn btn-lg btn-primary' %>
    </div>
  </div>
  <hr class="col-8 offset-2">
    <br class="clr" />
<% end %>
</div>

app/views/instructor/courses/new.html.erb
<br />
<div class="booyah-box col-10 offset-1">
  <h1>Add a new course</h1>
   <%= simple_form_for @course, url: instructor_courses_path do |f| %>
    <%= f.input :title %>
    <%= f.input :description %>
    <%= f.input :cost %>
    <%= f.input :image %>
    <br />
    <%= f.submit "Create", class: 'btn btn-primary' %>
    <br />
  <% end %>
  <br />
</div>

app/views/instructor/courses/show.html.erb
<script>
  $(function() {
    $('.new-lesson-button').click(function( event ) {
   var lessonUrl = $( event.target).data('lesson-url');
    $('#newLessonForm').attr('action', lessonUrl);
  });
    $('.lessons').sortable({
      update: function( event, ui ) {
        $.ajax({
          type: 'PUT',
          url: ui.item.data('update-url'),
          dataType: 'json',
          data: { lesson: { row_order_position: ui.item.index() } }
        });
      }
    });


    $('.sections').sortable({
      update: function( event, ui ) {
        $.ajax({
          type: 'PUT',
          url: ui.item.data('update-url'),
          dataType: 'json',
          data: { section: { row_order_position: ui.item.index() } }
        });
      }
    });

  });
</script>

<br />
<div class="booyah-box col-10 offset-1">
  <h1 class="text-center"><%= current_course.title %></h1>
  <%= image_tag current_course.image.url, class: 'img-fluid' %>

  <div class="text-center">
    <!-- Button trigger modal -->
    <button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#newSectionModal">
      Add a new section...
    </button>
  </div>

  <ul class="sections">
    <% current_course.sections.rank(:row_order).each do |section| %>
      <li data-update-url="<%= instructor_section_path section %>" class="section-li">
        <div class="header float-left">
          <span class="fa fa-ellipsis-v"></span>
          <%= section.title %>
        </div>

       <!-- Button trigger modal -->
        <button type="button" class="btn btn-primary btn-lg float-right new-lesson-button" data-toggle="modal" data-target="#newLessonModal" data-lesson-url="<%= instructor_section_lessons_path(section) %>">
          New Lesson...
        </button>

        <br class="clr" />
        <br class="clr" />

        <ul class="lessons">
          <% section.lessons.rank(:row_order).each do |lesson| %>
            <li data-update-url="<%= instructor_lesson_path lesson %>">
              <div class="row">
                <div class="col-1">
                  <br />
                  <span class="fa fa-ellipsis-v"></span>
                </div>
                <div class="col-11 text-center">
                  <p>
                    <b><%= lesson.title %></b>
                  </p>
                  <p>
                    <%= lesson.subtitle %>
                  </p>
                </div>
              </div>
              <br class="clr" />
            </li>
          <% end %>
        </ul>
        <br class="clr" />
      </li>
    <% end %>
  </ul>
</div>


<!-- Modal -->
<div class="modal fade" id="newSectionModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
        <h4 class="modal-title" id="newSectionModalLabel">Add a new section</h4>
      </div>
      <%= simple_form_for @section, url: instructor_course_sections_path(current_course) do |f| %>
        <div class="modal-body">
          <%= f.input :title %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <%= f.submit "Add a section", class: 'btn btn-primary' %>
        </div>
      <% end %>
    </div>
  </div>
</div>






<!-- Modal -->
<div class="modal fade" id="newLessonModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
        <h4 class="modal-title" id="newLessonModalLabel">Add a new lesson</h4>
      </div>
      <form accept-charset="UTF-8" action="#" class="simple_form new_lesson" enctype="multipart/form-data" id="newLessonForm" method="post" novalidate="novalidate"><div style="margin:0;padding:0;display:inline"><input name="utf8" type="hidden" value="✓" /><input name="authenticity_token" type="hidden" value="cWn+DdJbIjqZajnzD956Ox4jjPXsnn7178AzOldv0XI=" /></div>
        <div class="modal-body">
          <%= f.input :title %>
          <%= f.input :subtitle %>
          <%= f.input :video %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <%= f.submit "Add the lesson", class: 'btn btn-primary' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

<!-- Button trigger modal -->
<button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#newLessonModal">
  New Lesson...
</button>

<!-- Modal -->
<div class="modal fade" id="newLessonModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
        <h4 class="modal-title" id="newLessonModalLabel">Add a new lesson</h4>
      </div>
     <%= simple_form_for @lesson, url: "#" do |f| %>
        <div class="modal-body">
          <%= f.input :title %>
          <%= f.input :subtitle %>
          <%= f.input :video %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <%= f.submit "Add the lesson", class: 'btn btn-primary' %>
        </div>
      <% end %>
    </div>
  </div>
</div>
</form>

  
 

app/views/instructor/lessons/show.html.erb
<br />

<div class="booyah-box col-10 offset-1">
  <h1><%= current_lesson.title %></h1>
  <p class="float-left">
    <%= current_lesson.subtitle %>
  </p>

  <% if current_lesson.next_lesson.present? %>
    <%= link_to lesson_path(current_lesson.next_lesson), class: 'btn btn-default float-right' do %>
         Next Lesson &nbsp;
      <span class="fa fa-forward"></span>
    <% end %>
  <% end %>

  <br class="clr" />
  <br />

  <video id="my-video" class="video-js vjs-big-play-centered vjs-fluid" controls preload="auto" width="auto" height="auto"
  poster="/assets/black.jpg" data-setup="{}">
    <source src="<%= current_lesson.video.to_s %>" type='video/mp4'>
    <noscript>
      <p class="vjs-no-js">
        To view this video please enable JavaScript, and consider upgrading to a web browser that
        <a href="http://videojs.com/html5-video-support/" target="_blank">supports HTML5 video</a>
      </p>
    </noscript>
  </video>
</div>

app/views/instructor/sections/new.html.erb
<br />
<div class="booyah-box col-10 offset-1">
  <h1>Add a new section</h1>
  <%= simple_form_for @section, url: instructor_course_sections_path(@course) do |f| %>
    <%= f.input :title %>
    <br />
    <%= f.submit "Add a section", class: 'btn btn-primary' %>
    <br />
    <br />
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Flixter</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
     <link href="http://vjs.zencdn.net/5.12.6/video-js.css" rel="stylesheet">
  </head>

  <body>
    <div id="flex-content-container">
     <nav class="navbar navbar-toggleable-md navbar-light bg-faded">
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <a class="navbar-brand" href="#">Flixter</a>

      <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
        <ul class="navbar-nav mr-auto mt-2 mt-md-0">
          <li class="nav-item">
             <%= link_to 'See All Courses', courses_path, class: 'nav-link' %>
          </li>

        </ul>
        <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="text" placeholder="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
      </div>
    </nav>

    <% if notice.present? %>
  <p class="alert alert-info"><%= notice %></p>
<% end %>
<% if alert.present? %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>
  <%= yield %>
  </div>
  <div id="footer">
      <div class="container">
        <b>Teachers</b>
        <br />
        <%= link_to 'Teach a Course', new_instructor_course_path %>
        <br />
        <%= link_to 'My Dashboard', dashboard_path %>
        </div>
      </div>
        <script src="http://vjs.zencdn.net/5.12.6/video.js"></script>
    <script src="http://vjs.zencdn.net/ie8/1.1.2/videojs-ie8.min.js"></script>

    <ul class="navbar-nav">
  <% if user_signed_in? %>
    <li class="nav-item">
      <%= link_to 'My Dashboard', dashboard_path, class: 'nav-link' %>
    </li>
    <li class="nav-item">
      <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'nav-link' %>
    </li>
  <% else %>
    <li class="nav-item">
      <%= link_to 'Sign in', new_user_session_path, class: 'nav-link' %>
    </li>
    <li class="nav-item">
      <%= link_to 'Sign up!', new_user_registration_path, class: 'nav-link' %>
    </li>
  <% end %>
</ul>

    
  </body>
</html> <div class="row">
      <div class="col-12 col-sm-3">
        <b>Teachers</b>
        <br />
        <%= link_to 'Teach a Course', new_instructor_course_path %>
        <br />
        <%= link_to 'My Dashboard', dashboard_path %>
      </div>
      <div class="col-12 col-sm-3">
        <b>About</b>
        <br />
        <%= link_to 'Team', team_path %>
        <br />
        <%= link_to 'Privacy Policy', privacy_path %>
         <br />
         <%= link_to 'Careers', careers_path %>
      </div>
      <div class="col-12 col-sm-3">
        <b>Contact</b>
        <br />
        Timgriffin1@gmail.com
        <br />
        One Times Square
        <br />
        New York, NY 10022
      </div>
      <div class="col-12 col-sm-3 social">
        <b>Social</b>
        <br />
        <br />
        <%= link_to 'http://github.com/timgriffin1/flixter' do %>
    <span class="fa fa-github-square fa-2x social-button"></span>
  <% end %>
        <span class="fa fa-github-square fa-2x social-button"></span>
        <span class="fa fa-facebook-square fa-2x social-button"></span>
        <span class="fa fa-twitter-square fa-2x social-button"></span>
      </div>
    </div>
  </div>
</div>

app/views/lessons/new.html.erb
<br />
<div class="booyah-box col-10 offset-1">
  <h1>Add a new lesson</h1>
    <%= simple_form_for @lesson, url: instructor_section_lessons_path(current_section) do |f| %>
    <%= f.input :title %>
    <%= f.input :subtitle %>
    <%= f.input :video %>
    <br />
    <%= f.submit "Add the lesson", class: 'btn btn-primary' %>
    <br />
    <br />
  <% end %>
</div>

app/views/lessons/show.html.erb
<br />

<div class="booyah-box col-10 offset-1">
  <h1><%= current_lesson.title %></h1>
  <p class="float-left">
    <%= current_lesson.subtitle %>
  </p>

  <% if current_lesson.next_lesson.present? %>
    <%= link_to "Next Lesson", lesson_path(current_lesson.next_lesson), class: 'btn btn-default float-right' %>
  <% end %>

  <br class="clr" />
  <br />

  <video id="my-video" class="video-js vjs-big-play-centered vjs-fluid" controls preload="auto"
  poster="<%= image_path('black.jpg') %>" data-setup="{}">
    <source src="<%= current_lesson.video.to_s %>" type='video/mp4'>
    <noscript>
      <p class="vjs-no-js">
        To view this video please enable JavaScript, and consider upgrading to a web browser that
        <a href="http://videojs.com/html5-video-support/" target="_blank">supports HTML5 video</a>
      </p>
    </noscript>
  </video>
</div>

app/views/static_pages/careers.html.erb
<br />

<div class="booyah-box col-10 offset-1">
  <h1>Careers</h1>

  <p>
    We are always looking for great people.  If you think you are a match email us!
  </p>
</div>

app/views/static_pages/index.html.erb
<div class="hero">
  <br />
  <div class="frosty  col-10 offset-1 text-center"> 
      <br />
    <h1> Learn Programming from the Pros</h1>
      <br />
    <h2> The Skills Needed for the 21st Century</h2>
      <br />
      <%= link_to 'Learn More', courses_path, class: 'btn btn-success' %>
       <br /><br />
  </div>
</div>

<br />
<div class="row feature text-center">
  <div class="col-12 col-sm">
     <h3>Amazing Courses</h3>
    <br />
    <p>Choose from any number of courses to study with amazing teachers.</p>
    
  </div>

  <div class="col-12 col-sm">
   <h3>Learn At Your Own Pace</h3>
    <br />
    <p>Enroll and access a courses archive of lessons.</p>
  </div>

  <div class="col-12 col-sm">
   <h3>Join our Community</h3>
    <br />
    <p>Learn with a community of like-minded individuals.</p>
  </div>
</div>

app/views/static_pages/privacy.html.erb
<br />

<div class="booyah-box col-10 offset-1">
  <h1>Privacy Policy</h1>

  <p>
    We don't believe in Privacy Policies because YOLO.
  </p>
</div>

app/views/static_pages/team.html.erb
<br />

<div class="booyah-box col-10 offset-1">
  <h1>Team</h1>

  <p>
    We would love you to join our team!
  </p>
</div>